[tool.poetry]
name = "couch"
version = "0.1.0"
description = ""
authors = ["Richard van der Oost <richard@vanderoost.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
